[package]
name = "huevos-importer"
version = "0.1.0"
edition = "2021"

[dependencies]
huevos-api = { path = "../api"}
huevos-entity = { path = "../entity"}
huevos-migration = { path = "../migration" }
huevos-common = { path = "../common"}

anyhow = "1.0.72"
clap = { version = "4", features = ["derive"] }
csaf = "0.5"
csaf-walker = { version = "0.5" }
sbom-walker = { version = "0.5" }
env_logger = "0.10.0"
log = "0.4.19"
packageurl = "0.3.0"
sea-orm = { version = "0.12", features = [ "sea-query-binder", "sqlx-postgres", "runtime-tokio-rustls", "macros" ] }
sea-orm-migration = "0.12.2"
sea-query = "0.30.0"
serde_json = "1.0.104"
spdx-rs = "0.5.3"
thiserror = "1"
time = "0.3"
tokio = { version = "1.30.0", features = ["full"] }
walker-common = "0.5"
url = "2.4.0"
sha2 = "0.10.6"
async-trait = "0.1"

